apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.name }}
  # WARNING: when making a copy of this config file make sure to change the service name to avoid changing the production service
  name: {{ .Values.serviceName }}
  selfLink: {{ .Values.serviceSelfLink }}
spec:
  {{- if .Values.servicePorts }}
  ports:
    {{- toYaml .Values.servicePorts | nindent 4 }}
  {{- end }}
  selector:
    run: {{ .Values.name }}
  type: ClusterIP